ansible-collections/hetzner.hcloud

- changelogs/changelog.yaml
- plugins/modules/hcloud_floating_ip.py
- plugins/modules/hcloud_floating_ip_info.py
- plugins/modules/hcloud_load_balancer.py
- plugins/modules/hcloud_load_balancer_network.py
- plugins/modules/hcloud_load_balancer_service.py
- plugins/modules/hcloud_load_balancer_target.py
- plugins/modules/hcloud_load_balancer_type_info.py
- plugins/modules/hcloud_network.py
- plugins/modules/hcloud_network_info.py
- plugins/modules/hcloud_server.py
- plugins/modules/hcloud_server_info.py
- plugins/modules/hcloud_volume.py
- plugins/modules/hcloud_volume_info.py
- tests/integration/targets/hcloud_load_balancer/tasks/main.yml
- tests/integration/targets/hcloud_load_balancer_network/aliases
- tests/integration/targets/hcloud_load_balancer_network/defaults/main.yml
- tests/integration/targets/hcloud_load_balancer_network/meta/main.yml
- tests/integration/targets/hcloud_load_balancer_network/tasks/main.yml
- tests/integration/targets/hcloud_load_balancer_service/aliases
- tests/integration/targets/hcloud_load_balancer_service/defaults/main.yml
- tests/integration/targets/hcloud_load_balancer_service/meta/main.yml
- tests/integration/targets/hcloud_load_balancer_service/tasks/main.yml
- tests/integration/targets/hcloud_load_balancer_target/aliases
- tests/integration/targets/hcloud_load_balancer_target/defaults/main.yml
- tests/integration/targets/hcloud_load_balancer_target/meta/main.yml
- tests/integration/targets/hcloud_load_balancer_target/tasks/main.yml
- tests/utils/gitlab/gitlab.sh
- tests/utils/gitlab/integration.sh
> Implement Load Balancers and Certificates and prepare release

- galaxy.yml
> Correct URLs

- changelogs/fragments/lb-allow-change-type.yml
- plugins/modules/hcloud_load_balancer.py
- tests/integration/targets/hcloud_load_balancer/tasks/main.yml
- tests/integration/targets/hcloud_server_network/aliases
> hcloud_load_balancer Allow changing the type of a Load Balancer

- plugins/modules/hcloud_load_balancer.py
- plugins/modules/hcloud_load_balancer_target.py
- tests/integration/targets/hcloud_load_balancer/tasks/main.yml
- tests/integration/targets/hcloud_load_balancer_target/defaults/main.yml
- tests/integration/targets/hcloud_load_balancer_target/tasks/main.yml
- tests/utils/gitlab/gitlab.sh
> Implement Label Selector and IP Targets

- plugins/modules/hcloud_certificate.py
- plugins/modules/hcloud_certificate_info.py
> Remove ANSIBLE_METADATA in hcloud_certificate and hcloud_certificate_info

- changelogs/fragments/gh-28-allow-setting-of-protection-on-creation.yml
- plugins/modules/hcloud_floating_ip.py
- plugins/modules/hcloud_load_balancer.py
- plugins/modules/hcloud_network.py
- plugins/modules/hcloud_server.py
- plugins/modules/hcloud_volume.py
- tests/integration/targets/hcloud_floating_ip/tasks/main.yml
- tests/integration/targets/hcloud_load_balancer/tasks/main.yml
- tests/integration/targets/hcloud_network/tasks/main.yml
- tests/integration/targets/hcloud_server/tasks/main.yml
- tests/integration/targets/hcloud_volume/tasks/main.yml
> Allow creating resources with protection

- changelogs/fragments/fix-idempotency-floating-ip.yml
- plugins/modules/hcloud_floating_ip.py
- tests/integration/targets/hcloud_floating_ip/tasks/main.yml
> Fix Floating IP assignment is not idempotent

- plugins/modules/hcloud_subnetwork.py
- shippable.yml
- tests/integration/targets/hcloud_load_balancer_network/tasks/main.yml
- tests/integration/targets/hcloud_subnetwork/aliases
- tests/integration/targets/hcloud_subnetwork/defaults/main.yml
- tests/integration/targets/hcloud_subnetwork/tasks/main.yml
> Add vSwitch Integration

- plugins/inventory/hcloud.py
- plugins/module_utils/hcloud.py
- plugins/modules/hcloud_certificate.py
- plugins/modules/hcloud_certificate_info.py
- plugins/modules/hcloud_datacenter_info.py
- plugins/modules/hcloud_floating_ip_info.py
- plugins/modules/hcloud_image_info.py
- plugins/modules/hcloud_load_balancer.py
- plugins/modules/hcloud_load_balancer_service.py
- plugins/modules/hcloud_load_balancer_target.py
- plugins/modules/hcloud_location_info.py
- plugins/modules/hcloud_network_info.py
- plugins/modules/hcloud_route.py
- plugins/modules/hcloud_server.py
- plugins/modules/hcloud_server_info.py
- plugins/modules/hcloud_server_network.py
- plugins/modules/hcloud_server_type_info.py
- plugins/modules/hcloud_ssh_key.py
- plugins/modules/hcloud_ssh_key_info.py
- plugins/modules/hcloud_volume.py
- plugins/modules/hcloud_volume_info.py
> Improve imports of APIException

- .gitlab-ci.yml
- changelogs/config.yaml
- plugins/inventory/hcloud.py
- plugins/modules/hcloud_floating_ip.py
- plugins/modules/hcloud_load_balancer_info.py
- plugins/modules/hcloud_load_balancer_network.py
- plugins/modules/hcloud_load_balancer_target.py
- plugins/modules/hcloud_network.py
- plugins/modules/hcloud_rdns.py
- plugins/modules/hcloud_route.py
- plugins/modules/hcloud_server_network.py
- plugins/modules/hcloud_subnetwork.py
- tests/integration/targets/hcloud_load_balancer_info/aliases
- tests/integration/targets/hcloud_load_balancer_info/defaults/main.yml
- tests/integration/targets/hcloud_load_balancer_info/meta/main.yml
- tests/integration/targets/hcloud_load_balancer_info/tasks/main.yml
- tests/utils/gitlab/gitlab.sh
This adds the `hcloud_load_balancer_info` module. Fixes #34 
hcloud_load_balancer_info
```paste below
```
> Add hcloud_load_balancer_info module

- plugins/inventory/hcloud.py
Addresses #39 
inventory/hcloud
> add token_env option to load token from custom env variable

- plugins/modules/hcloud_load_balancer.py
- plugins/modules/hcloud_load_balancer_service.py
- plugins/modules/hcloud_load_balancer_target.py
- plugins/modules/hcloud_volume.py
Fix Sanity tests
```paste below
```
> Fix Sanity tests: doc-default-does-not-match-spec

- .azure-pipelines/azure-pipelines.yml
- plugins/inventory/hcloud.py
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.9.txt
- tests/sanity/requirements.txt
- tests/utils/gitlab/gitlab.sh
- tests/utils/gitlab/integration.sh
- tests/utils/shippable/shippable.sh
* As we only have a small number of sanity tests, don't group them
* Fix (or ignore) `shellcheck` errors.
> [WIP] AZP fixes

- plugins/modules/hcloud_ssh_key.py
- tests/integration/targets/hcloud_ssh_key/defaults/main.yml
- tests/integration/targets/hcloud_ssh_key/tasks/main.yml
- tests/utils/gitlab/sanity.sh
> Improve error handling ssh key create

- .gitignore
- plugins/modules/hcloud_firewall.py
- plugins/modules/hcloud_server.py
- tests/integration/targets/hcloud_firewall/aliases
- tests/integration/targets/hcloud_firewall/defaults/main.yml
- tests/integration/targets/hcloud_firewall/meta/main.yml
- tests/integration/targets/hcloud_firewall/tasks/main.yml
- tests/integration/targets/hcloud_server/tasks/main.yml
- tests/utils/gitlab/sanity.sh
> Implement Firewall Support

- .azure-pipelines/azure-pipelines.yml
https://github.com/ansible-collections/overview/issues/45#issuecomment-807391460
> AZP: update default test container version

- .gitlab-ci.yml
- plugins/modules/hcloud_certificate.py
- tests/integration/targets/hcloud_certificate/defaults/main.yml
- tests/integration/targets/hcloud_certificate/tasks/main.yml
> Add managed certs support

- changelogs/fragments/74-hcloud_server-improve-error-message-images.yml
- plugins/modules/hcloud_server.py
- tests/integration/targets/hcloud_server/tasks/main.yml
> hcloud_server - improve image handling

- changelogs/fragments/inventory-fix-server-type-wrong-value.yml
- plugins/inventory/hcloud.py
> Fix inventory: server type had the wrong value

- changelogs/fragments/hcloud-server-py36.yaml
- plugins/modules/hcloud_server.py
- tests/integration/targets/hcloud_server/tasks/main.yml
> Fix compatibility of hcloud_server module with python version lower than python 3.6

- plugins/modules/hcloud_firewall.py
- tests/integration/targets/hcloud_firewall/tasks/main.yml
> Improve handling of out rules in hcloud_firewall

- plugins/inventory/hcloud.py
Fixes https://github.com/ansible-collections/hetzner.hcloud/issues/86
```paste below
```
> Add full collection name as option to inventory plugin

- changelogs/fragments/hcloud_server-improve-error-message-on-not-existing-firewall.yml
- plugins/modules/hcloud_server.py
- tests/integration/targets/hcloud_server/tasks/main.yml
> hcloud_server: Improve Error Message when attaching a not existing firewall

- tests/integration/targets/hcloud_certificate_info/meta/main.yml
- tests/integration/targets/hcloud_certificate_info/tasks/main.yml
> Fix hcloud_certificate_info test

- changelogs/fragments/hcloud_firewall-add-description-field-to-rules.yml
- plugins/modules/hcloud_firewall.py
- tests/integration/targets/hcloud_firewall/tasks/main.yml
```paste below
Add description field to firewall rules
```
> Add description field to firewall rules

- changelogs/fragments/hcloud_placement_group.yml
- plugins/modules/hcloud_placement_group.py
- plugins/modules/hcloud_server.py
- plugins/modules/hcloud_server_info.py
- tests/integration/targets/hcloud_placement_group/aliases
- tests/integration/targets/hcloud_placement_group/defaults/main.yml
- tests/integration/targets/hcloud_placement_group/meta/main.yml
- tests/integration/targets/hcloud_placement_group/tasks/main.yml
- tests/integration/targets/hcloud_server/tasks/main.yml
hcloud_placement_group
```paste below
Add support for placement groups
```
> Placement groups

- changelogs/fragments/hcloud_rdns-add-support-for-load-balancers.yml
- plugins/modules/hcloud_rdns.py
- tests/integration/targets/hcloud_rdns/defaults/main.yml
- tests/integration/targets/hcloud_rdns/tasks/main.yml
hcloud_rdns
```paste below
hcloud_rdns Add support for load balancer
```
> Dns ptr records for load balancer

- changelogs/fragments/inventory-network-templating.yml
- plugins/inventory/hcloud.py
Fixes https://github.com/ansible-collections/hetzner.hcloud/issues/105
```paste below
```
> inventory - support jinjia templating within `network`

- plugins/inventory/hcloud.py
- tests/sanity/ignore-2.14.txt
https://github.com/ansible-collections/news-for-maintainers/issues/13
Dear maintainers,
I'd like to ask you to track the news-for-maintainers themselves in the future if possible
Thanks!
> Sanity tests: copy ignore-2.13.txt to ignore-2.14.txt

- plugins/modules/hcloud_load_balancer_target.py
Some examples don't use the right type
hcloud_load_balancer_target
```paste below
```
> hcloud_load_balancer_target: fix types in examples

- tests/integration/targets/hcloud_datacenter_info/tasks/main.yml
There are now 4 DCs (Ashburn DC1 was added)
```paste below
```
> tests: hcloud_datacenter_info: fix count should be 4

- .azure-pipelines/azure-pipelines.yml
Applies changes requested in https://github.com/ansible-collections/news-for-maintainers/issues/18
> Test on py3.9

- changelogs/fragments/hcloud_firewall-esp-gre.yml
- plugins/modules/hcloud_firewall.py
Fixes https://github.com/ansible-collections/hetzner.hcloud/issues/157
```paste below
```
> hcloud_firewall: Add support for esp and gre

- plugins/doc_fragments/hcloud.py
- plugins/modules/hcloud_certificate.py
Closes https://github.com/ansible-collections/hetzner.hcloud/issues/79
```paste below
```
> Docs: Document possibility to set the module api_token via env var

- changelogs/fragments/hcloud_inventory.yml
- plugins/inventory/hcloud.py
Fixes https://github.com/ansible-collections/hetzner.hcloud/issues/114
```paste below
```
> Inventory Plugin: Add support for changing the name of the top level group all servers are added to

- changelogs/fragments/hcloud_firewall-deletion.yml
- plugins/modules/hcloud_firewall.py
Fixes https://github.com/ansible-collections/hetzner.hcloud/issues/112
```paste below
```
> hcloud_firewall: Fix race condition on deletion of firewalls

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/hcloud_firewall-deletion.yml
- changelogs/fragments/hcloud_firewall-esp-gre.yml
- changelogs/fragments/hcloud_inventory.yml
- changelogs/fragments/hcloud_server_backup_window.yml
- changelogs/fragments/hcloud_volume_server_none.yml
- galaxy.yml
> Prepare Release 1.9.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/hcloud_server-removed-networks.yml
- galaxy.yml
> chore: prepare v1.9.1

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/inventory-connect-via-ipv6.yml
- changelogs/fragments/inventory-handle-invalid-connect-with.yml
- changelogs/fragments/inventory-ipv6-adress-variable.yml
- changelogs/fragments/inventory-private-network-info.yml
- changelogs/fragments/server-private-networks-info.yml
- galaxy.yml
> chore: prepare v1.10.0

- .gitlab-ci.yml
Update the CI definition for our company internal gitlab-ci setup.
> ci(gitlab): cleanup and use latest python&ansible versions

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/server-fix-backups.yml
- changelogs/fragments/server-race-condition-pg-attach.yml
- galaxy.yml
> chore: prepare 1.10.1

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
> chore: prepare v1.12.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/create_primary_ip_info.yml
- changelogs/fragments/server-type-deprecation.yml
- changelogs/fragments/server_error_deprecated_image.yml
> chore: prepare v1.13.0

- tests/integration/targets/hcloud_floating_ip/tasks/main.yml
- tests/integration/targets/hcloud_primary_ip/tasks/main.yml
Fixes the flakiness of some tests, by making sure the ressources aren't present before we start testing.
> test: clean ressources before testing

- changelogs/fragments/add-field-expose_routes_to_vswitch.yml
- plugins/modules/hcloud_network.py
- plugins/modules/hcloud_network_info.py
- tests/integration/targets/hcloud_network/defaults/main.yml
- tests/integration/targets/hcloud_network/tasks/main.yml
- tests/integration/targets/hcloud_network_info/tasks/main.yml
Add expose_routes_to_vswitch field to network modules.
`hcloud_network`
`hcloud_network_info`
> feat(network): add expose_routes_to_vswitch field

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/add-field-expose_routes_to_vswitch.yml
- galaxy.yml
> chore: prepare v1.14.0

- changelogs/fragments/fix-facts-modules-deprecation.yml
- plugins/modules/hcloud_image_info.py
- plugins/modules/hcloud_location_info.py
- plugins/modules/hcloud_server_type_info.py
The old facts deprecation warnings had some small nits.
> fix: facts deprecation warnings and result

- README.md
Update and add more details to the release process documentation. This is a first step towards a scripted release process.
> docs: add more details to release process

- plugins/modules/hcloud_server_network.py
Cherry-picked from the https://github.com/ansible-collections/hetzner.hcloud/pull/9
`hcloud_server_network`
> docs(hcloud_server_network): fix modules params

- CHANGELOG.rst
- changelogs/changelog.yaml
Update the changelog from the last release on the stable-1 branch.
> chore: copy v1.16.0 changelog entries

- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.13.txt
- tests/sanity/ignore-2.14.txt
- tests/sanity/ignore-2.15.txt
- tests/sanity/ignore-2.16.txt
- tests/utils/shippable/check_matrix.py
- tests/utils/shippable/sanity.sh
- tests/utils/shippable/timing.py
Fix some errors that appeared while running the ansible devel sanity tests. https://github.com/ansible-collections/hetzner.hcloud/pull/270/checks?check_run_id=15163296675
> test: exclude test scripts from sanity test

- .azure-pipelines/scripts/aggregate-coverage.sh
- .azure-pipelines/scripts/publish-codecov.sh
- .azure-pipelines/scripts/report-coverage.sh
- .azure-pipelines/scripts/run-tests.sh
- .pre-commit-config.yaml
- tests/utils/gitlab/gitlab.sh
- tests/utils/gitlab/sanity.sh
- tests/utils/shippable/shippable.sh
This adds 2 pre-commit hooks used to lint shell script.
- shfmt to format shell scripts: https://github.com/mvdan/sh
- shellcheck to find errors/bad practices https://github.com/koalaman/shellcheck
> chore: add shell pre-commit hooks

- plugins/inventory/hcloud.py
Some leftovers from #291 
A changelog fragment was already added in the #291
> feat: use collection version for the inventory user agent

- changelogs/fragments/allow-caching-hcloud-inventory.yml
- plugins/inventory/hcloud.py
Add the ability to cache the hcloud inventory.
Fixes #124
`inventory`
> feat: allow caching the hcloud inventory

- changelogs/fragments/query-hcloud_floating_ip_info-by-name.yml
- plugins/modules/hcloud_floating_ip_info.py
- tests/integration/targets/hcloud_floating_ip_info/tasks/test.yml
Fixes #302 
The feature was missing, this make the floating_ip_info module consistent with what is expected to be implemented. 
floating_ip_info
> feat: query floating ip info by name

- changelogs/fragments/add-target-health-status-in-hcloud_load_balancer_info.yml
- plugins/modules/hcloud_load_balancer_info.py
- tests/integration/targets/hcloud_load_balancer_info/tasks/test.yml
Fixes #221
hcloud_load_balancer_info
>  feat: target health status in hcloud_load_balancer_info

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/add-target-health-status-in-hcloud_load_balancer_info.yml
- changelogs/fragments/allow-caching-hcloud-inventory.yml
- changelogs/fragments/consistently-fail-on-invalid-id.yml
- changelogs/fragments/query-hcloud_floating_ip_info-by-name.yml
- changelogs/fragments/use-collection-version-in-user-agent.yml
- galaxy.yml
- plugins/module_utils/version.py
> chore: prepare v2.1.0

- .flake8
- plugins/inventory/hcloud.py
- plugins/modules/hcloud_floating_ip.py
- plugins/modules/hcloud_load_balancer_network.py
- plugins/modules/hcloud_load_balancer_service.py
- plugins/modules/hcloud_load_balancer_target.py
- plugins/modules/hcloud_server.py
Replace string interpolation with f-strings. Improves readability, and should help prevent #309
> refactor: use f-strings

- .pre-commit-config.yaml
- plugins/modules/hcloud_load_balancer_info.py
- plugins/modules/hcloud_load_balancer_target.py
This check will run a linter against the documentation. I was already able to fix a few errors.
> chore: add antsibull-docs lint-collection pre-commit hook

- Makefile
- pyproject.toml
- requirements.txt
Add configuration files to simplify the dev setup for the project. This will help IDEs to provide insight during development.
Pylint is already run by the ansible-test sanity checks.
> chore: add dev config

- tests/unit/module_utils/test_hcloud.py
We had a race condition between 2 Pull Requests (#336 and #325) and everything didn't go through the test pipeline. Fixing it now.
> test: fix AnsibleHCloud module unit tests

- .github/workflows/release-please.yml
This reverts commit 796ab1c1ae694a4485995a56f08ad54de2ae4cf8.
> ci: revert skip azp on release please commits (#338)

- .ansible-lint
- tests/integration/targets/hcloud_load_balancer/tasks/cleanup.yml
- tests/integration/targets/hcloud_load_balancer/tasks/test.yml
Use the new testing framework and clean up the load_balancer tests.
> test: rework load_balancer module tests

- plugins/modules/hcloud_load_balancer.py
- tests/integration/targets/hcloud_load_balancer/tasks/test.yml
Allow to configure load balancers algorithm.
Closes #289
Depends on #367 
hcloud_load_balancer
> feat: add load_balancer algorithm option

- .ansible-lint
- .pre-commit-config.yaml
- tests/integration/targets/hcloud_rdns/meta/main.yml
- tests/integration/targets/hcloud_rdns/tasks/cleanup.yml
- tests/integration/targets/hcloud_rdns/tasks/prepare.yml
- tests/integration/targets/hcloud_rdns/tasks/test.yml
Use the new testing framework for the rdns integration tests.
> test: improve rdns integration using the testing framework

- plugins/modules/hcloud_certificate.py
Closes #374 
Closes #375
hcloud_certificates
> docs: fix certificates module options and examples

- examples/inventory.hcloud.yml
- plugins/inventory/hcloud.py
- plugins/module_utils/client.py
Improve the performance of the inventory plugin by:
- Cache client requests
- Move servers `status` filtering to query params.
> fix(inventory): improve performance

- plugins/inventory/hcloud.py
Outlines the fact that `type` and `server_type` are the same value.
> refactor: reorder inventory server type host vars

- plugins/modules/firewall.py
- Improve link to other reference (plugins/modules/options)
- Add details to option description.
- Reorder options for readability
> docs: improve firewall module documentation

- plugins/inventory/hcloud.py
- tests/sanity/ignore-2.13.txt
- tests/sanity/ignore-2.14.txt
- tests/sanity/ignore-2.15.txt
- tests/sanity/ignore-2.16.txt
- Re add some examples that were removed during a dep upgrade.
- Improve link to other reference (plugins/modules/options)
- Remove duplicate docs.
> docs: improve hcloud inventory documentation

- .ansible-lint
- tests/integration/targets/network/aliases
- tests/integration/targets/network/defaults/main/main.yml
- tests/integration/targets/network/tasks/cleanup.yml
- tests/integration/targets/network/tasks/test.yml
Implement the new test framework for the network tests, and reenable the network tests
>  test: use testing framework for network integration tests 

- changelogs/fragments/primary-ip-assigned-to-server.yml
- changelogs/fragments/primary-ip-auto-delete.yml
- plugins/modules/primary_ip.py
- plugins/modules/primary_ip_info.py
- tests/integration/targets/primary_ip/tasks/cleanup.yml
- tests/integration/targets/primary_ip/tasks/prepare.yml
- tests/integration/targets/primary_ip/tasks/test.yml
> feat: assign primary ip to a server on create

- plugins/modules/server.py
Leverage the alias feature from the argument spec, and re-declare the deprecation of the `force_upgrade` argument.
> docs: use argument spec to mark `force_upgrade` as deprecated

- changelogs/fragments/server-use-id-or-name.yml
- plugins/modules/server.py
- Allow passing either the name or the ID of a resource to the different arguments of the server module.
- Split the code into multiple smaller function and improve the code.
- Improve the module arguments documentation.
- Refactor and cleanups.
> feat: use resources name or ID in server module arguments

- tests/integration/targets/firewall/tasks/test.yml
- tests/integration/targets/floating_ip/tasks/test.yml
- tests/integration/targets/load_balancer/tasks/test.yml
- tests/integration/targets/network/tasks/test.yml
- tests/integration/targets/primary_ip/tasks/test.yml
- tests/integration/targets/server/tasks/test_basic.yml
- tests/integration/targets/server/tasks/test_firewalls.yml
- tests/integration/targets/server/tasks/test_validation.yml
- tests/integration/targets/ssh_key/tasks/test.yml
- tests/integration/targets/volume/tasks/test.yml
Ensure the error code is correct and replace the error message check in some cases.
> test: check for api error code when possible

- changelogs/fragments/inventory-fix-serialization.yml
- plugins/inventory/hcloud.py
- tests/unit/inventory/test_hcloud.py
Fix https://github.com/ansible-collections/hetzner.hcloud/issues/495
Related to https://github.com/ansible-collections/hetzner.hcloud/pull/477
inventory
> fix(inventory): ensure host ipv6 variable is json serializable

- tests/integration/targets/network/tasks/test.yml
The new network service has a different error message.
> test: update network delete protection error message

- plugins/module_utils/client.py
- plugins/module_utils/hcloud.py
- tests/unit/module_utils/test_client.py
Replace the local function with the exponential_backoff_function from hcloud-python
> refactor: reuse `exponential_backoff_function` from hcloud-python

- tests/integration/targets/floating_ip/tasks/test.yml
- tests/integration/targets/load_balancer/tasks/test.yml
- tests/integration/targets/network/tasks/test.yml
- tests/integration/targets/primary_ip/tasks/test.yml
- tests/integration/targets/server/tasks/test_basic.yml
- tests/integration/targets/server/tasks/test_firewalls.yml
- tests/integration/targets/server/tasks/test_validation.yml
- tests/integration/targets/ssh_key/tasks/test.yml
- tests/integration/targets/volume/tasks/test.yml
Reduce tests flakiness, as human error messages may change over time.
> test: do not check error messages meant for humans

- .ansible-lint
- tests/integration/targets/load_balancer_network/tasks/cleanup.yml
- tests/integration/targets/load_balancer_network/tasks/prepare.yml
- tests/integration/targets/load_balancer_network/tasks/test.yml
Use the new testing framework for the load_balancer_network integration tests.
> test: improve `load_balancer_network` integration using new framework

- .azure-pipelines/azure-pipelines.yml
See https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
> test: run devel (ansible-core 2.18) tests with python 3.13

- changelogs/fragments/only-rebuild-existing-servers.yml
- plugins/modules/server.py
Fixes #580
A freshly created server must not be rebuild.
server
> fix: only rebuild existing servers, skip rebuild if it was just created

- .gitignore
Ansible put some runtime files in there, e.g. .lock files.
> chore: ignore .ansible dir

- changelogs/fragments/renaming-a-server.yml
- plugins/modules/server.py
- tests/integration/targets/server/tasks/test_basic.yml
Fixes #600
Allow renaming a server by passing its id and its new name.
server
> feat: allow renaming a server
