ansible-collections/hetzner.hcloud

changelogs/inventory-allow-usage-of-pre-migration-configuration-fuiles.yml
plugins/inventory/hcloud.py
plugins/modules/hcloud_load_balancer.py
plugins/modules/hcloud_load_balancer_service.py
tests/integration/targets/hcloud_load_balancer/tasks/main.yml
tests/utils/gitlab/gitlab.sh
tests/utils/gitlab/integration.sh

Bugfix: allow hcloud.yml and hcloud.yaml again as inventory configuration.
Before the migration to the collection the configuration files allowed everything that ends with `hcloud`. The migrations to our collection repo changed that to everything that ends with `hetzner.hcloud.hcloud.yml/hetzner.hcloud.hcloud.yaml`. This reverts that change to allow everything that ends with `hcloud.yml/hcloud.yaml`.
hcloud inventory plugin
```paste below
```

Fix inventory plugin does not work with old configuration files

---

changelogs/fragments/gh7-allow-enabling-of-backups-on-server-creation.yml
plugins/modules/hcloud_server.py
tests/integration/targets/hcloud_server/tasks/main.yml

This allows the creation of Servers with backups enabled in one step instead of needing an additional step just for enabling the backups.
Fixes: #7 
hcloud_server
```paste below
```

Allow the creation of servers with enabled backups

---

plugins/inventory/hcloud.py

the private_ipv4 option was missing from the connect_with documentation section

document private_ipv4 connect_with option

---

plugins/modules/hcloud_rdns.py
tests/integration/targets/hcloud_rdns/defaults/main.yml
tests/integration/targets/hcloud_rdns/tasks/main.yml

hcloud_rdns
This came up with #25. We planned to have the Floating IPs within the `hcloud_rdns` module but just missed to add the functionality while implementing the `hcloud_floating_ip` modules
```paste below
```

Allow setting Floating IP RDNS entries with hcloud_rdns

---

plugins/modules/hcloud_server_network.py
tests/integration/targets/hcloud_server_network/tasks/main.yml

This MR allows updating hcloud_server_network. Only alias IPs are updateable, all the other values are not updateable without reattachment (deleting hcloud_server_network)
Fixes #40 
hcloud_server_network
```paste below
```

Allow updating hcloud_server_network (alias IPs)

---

plugins/inventory/hcloud.py

Fixes #44. The support was unintentionally dropped because of a pylint warning within our own CI, that was fixed by using the same version as Ansible itself does.
Dynamic Inventory
```paste below
```

Restore Python 2.7 support

---

plugins/modules/hcloud_network_info.py

This was brought up by a customer via Ticket. When a server was created from a (now) deleted image, the image within the API is returned as "null/None". In all other modules we handled this correctly, only the hcloud_network_info module was missing.
hcloud_network_info
```paste below
```

Fix image NoneType exception in hcloud_network_info

---

changelogs/fragments/64-hcloud_server_fix_checkmode_state_started.yml
plugins/modules/hcloud_server.py

Closes #54 
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'AttributeError'>, 'NoneType' object has no attribute 'status'
fatal: [mon1.ngine.ch]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_hcloud_server_payload_uyrhr_4g/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 503, in start_server\nAttributeError: 'NoneType' object has no attribute 'status'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line …
```

hcloud_server: fix traceback in check mode

---

changelogs/fragments/70-no_log_security_fixes.yml
plugins/modules/hcloud_certificate.py
plugins/modules/hcloud_server.py

Fix sanity https://github.com/ansible-collections/hetzner.hcloud/pull/69

[security] hcloud_certificate, hcloud_server: define no_log values for private_key and ssh_keys parameters

---

changelogs/fragments/71-hcloud_firewall_fix_idempotence.yml
plugins/modules/hcloud_firewall.py
plugins/modules/hcloud_server.py
tests/integration/targets/hcloud_firewall/tasks/main.yml
tests/integration/targets/hcloud_server/tasks/main.yml

hcloud_firewall:
Fix idempotence for firewall rules, fixes always returned changed. 
IMHO there were 2 issues:
1. desitnation_ip was None if unset and API returns List of strings.
2. comparsion of rules was comparing list of objects between list of dicts which is never equal
hcloud_server:
the firewall handling in server did also return changed. I refactored a bit to make the fix.
hcloud_server
```paste below
```

hcloud_firewall, hcloud_server: fix idempotence

---

plugins/inventory/hcloud.py

This change passes the `token` property through the jinja templating engine so that the token can for example be retrieved via a lookup plugin (password store, etc.). 
Fixes #48
hcloud inventory_plugin

Expand template instructions in 'token' property

---

changelogs/fragments/hcloud-server-server-type.yaml
plugins/modules/hcloud_server.py
tests/integration/targets/hcloud_server/tasks/main.yml

Improves the error handling when an unknown server type is given. Before the module crashed when passing the data to the create/resize calls.
hcloud_server
```paste below
```

hcloud_server Improve error handling when using not existing server types

---

changelogs/fragments/hcloud_volume-force-detach-before-deletion.yml
plugins/modules/hcloud_volume.py

Force detaching of volumes before deleting when they are still attached to a server. This makes it easier for tools like molecule to see the correct state.
Fixes #47 
```paste below
```

hcloud_volume: Force detaching volume on deletion

---

changelogs/fragments/hcloud_server_default-backups-to-none.yml
plugins/modules/hcloud_server.py

When the default is set to false, it always disables the backups when a user do not specify the backups to True always. This shouldn't be the case.
Fixes #https://github.com/ansible-collections/hetzner.hcloud/issues/87
```paste below
```

hcloud_server: Change backups default to None

---

changelogs/fragments/hcloud_rdns-improve-validation-of-input.yml
plugins/modules/hcloud_rdns.py
tests/integration/targets/hcloud_rdns/tasks/main.yml

This came up in #98. When specifying a resource that does not exist we currently fail in an ugly way (NoneType Exception). This shouldn't be the case.
Fixes #98 
hcloud_rdns
```paste below
```

hcloud_rdns improve error message on not existing server/Floating IP

---

plugins/modules/hcloud_certificate.py
plugins/modules/hcloud_firewall.py
plugins/modules/hcloud_floating_ip.py
plugins/modules/hcloud_load_balancer.py
plugins/modules/hcloud_load_balancer_service.py
plugins/modules/hcloud_network.py
plugins/modules/hcloud_placement_group.py
plugins/modules/hcloud_server.py
plugins/modules/hcloud_ssh_key.py
plugins/modules/hcloud_volume.py

Fix a repeating typo in the docs: "does not exist**s**" shouldn't have the last 's'.

Docs: fix typo

---

plugins/inventory/hcloud.py

It is quite often required to only include the `running` servers in the Ansible dynamic inventory. While it is possible to create `keyed_groups` for that purpose, having an option to filter out the servers with a different status directly in the plugin configuration in the same way as with `locations`, `types`, and `networks` looks simple and attractive.
Inventory Plugin

add server `status` as an option to filter the server inventory list

---

plugins/modules/hcloud_server_network.py

Hey, I found a bug that the `hcloud_server_network` module doesn't apply changes when the option `alias_ips` is changed. 
For detecting a change, the sorted list of the current alias IPs is compared to the given list. 
The lists are sorted with `sort()`, but `sort()` updates the list itself and always returns `None`. 
Using `sort()` in an if-condition can therefore never detect a change. 
My suggestion is to use `sorted()` instead. 
`hcloud_server_network` module

hcloud_server_network: fixes changed alias_ips by using sorted

---

plugins/modules/hcloud_load_balancer_network.py
plugins/modules/hcloud_load_balancer_service.py
plugins/modules/hcloud_load_balancer_target.py
tests/integration/targets/hcloud_load_balancer_network/tasks/main.yml
tests/integration/targets/hcloud_load_balancer_service/tasks/main.yml
tests/integration/targets/hcloud_load_balancer_target/tasks/main.yml

Traceback if loadbalancer does not exist:
```
failed: [xyz -> localhost] (item={'protocol': 'http', 'port': 80}) => {"ansible_loop_var": "service", "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_service_payload_fi4sysuo/ansible_hetzner.hcloud.hcloud_load_balancer_service_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer_service.py\", line 346, in _get_load_balancer\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_service_payload_fi4sysuo/ansible_hetzner.hcloud.hcloud_load_balancer_service_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer_service.py\", line 486, in _get_load_balancer_service\nAttributeError: 'NoneType' object has …
```

loadbalancer_: improve error handlings

---

changelogs/fragments/flexible-networks-hcloud-server-info.yml
plugins/modules/hcloud_server.py
plugins/modules/hcloud_server_info.py
tests/integration/targets/hcloud_server_info/tasks/main.yml

- hcloud_server_info - fix crash when having servers without IPs (flexible networks)
- hcloud_server - When state stopped and server is created, do not start the server
Fixes #142 This was overseen while developing the changes for flexible networks
Additionally, it fixes a smaller bug in the hcloud_server module that might cause confusion again with the flexible networks options (The API returns an error when you try to create a server without any connectivity without `start_after_create=False`, this case is now covered when using `state=stopped`).
```paste below
```

hcloud_server_info: Add missing support for flexible networks

---

plugins/modules/hcloud_network_info.py

First of all, thank you for providing the Ansible community with an easy way to manage their HCloud infrastructure.
I'm opening this PR on behalf of the company I work for, Peerox GmbH.
Best regards,
Konstantin Köhring
This fixes the behavior if there is a server without direct internet connectivity in the examined network.
Previously, the module would throw an AttributeError because server.public_net.ipv4/ipv6 is None in this case. Now the None propagates correctly.
Fixes #155 
hetzner.hcloud.network_info module
Steps to reproduce:
1. Create a server with disabled public network (no IPv6 and no IPv4)
2. Attach the server to a private network
3. Try to invoke `hetzner.hcloud.hcloud_network_info` with `{"name": "NAME_OF_THE_PRIVATE_NETWORK"}`
before:
```
exception: …
```

Fix hcloud_network_info failing with Servers without internet connectivity

---

changelogs/fragments/hcloud_server-removed-networks.yml
plugins/modules/hcloud_server.py

Changes the default  of field `hcloud_server.networks` to `None` (from `[]`) and only reconcile attached networks if value is `not None`.
Fixes #174
`hetzner.hcloud.hcloud_server`
-

fix(server): attached networks are removed when not defined in hcloud_server

---

changelogs/fragments/inventory-connect-via-ipv6.yml
plugins/inventory/hcloud.py

Add a new `connect_with` option `public_ipv6` that uses the first address from the servers publically-routed ipv6 network.
Fixes #173
inventory-plugin

feat(inventory): connect via public ipv6 address

---

plugins/inventory/hcloud.py

Allow token to be provided through extra-vars.
Allows "dynamic" insertion of the token without changing the environment variables
Fixes #181 
hetzner.hcloud.hcloud
Only thing I am not perfectly sure about is, if one can safely use `self._compose` and `self._compose` in a custom plugin.

Inventory plugin: Allow token to be provided through extra-vars.

---

plugins/modules/hcloud_server.py
plugins/modules/hcloud_server_info.py

Fixes https://github.com/ansible-collections/hetzner.hcloud/issues/169
Returns info about networks with name and internal IP within hcloud_server_info and hcloud_server response.
**Note**: Adapted from [minitriga](https://github.com/minitriga) in original PR https://github.com/ansible-collections/hetzner.hcloud/pull/170
~~~
ok: [localhost] => changed=false 
hcloud_server_info:
- backup_window: null
datacenter: hel1-dc2
delete_protection: false
id: '234'
image: None
ipv4_address: null
ipv6: null
labels: {}
location: hel1
name: sa-alex-gittings-ipf-6.0.0.14
placement_group: null
private_networks:
- SA
private_networks_info:
- ip: 10.194.50.15
name: SA
rebuild_protection: false
rescue_enabled: false
server_type: cx41
status: running
~~~
Feature Pull Request
hcloud_server
hcloud_server_info

Add private_networks_info with info dict containing name and private ip

---

plugins/modules/hcloud_server.py

Increase `wait_until_finished` timeout for server rebuild because default of `100` is too low.
module: hcloud_server
Default's `wait_unit_finished()` timeout is `100`, see https://github.com/hetznercloud/hcloud-python/blob/32bd2ecea280aebee62305fb7e4a2d0aa90540b8/hcloud/actions/client.py#L10. Increasing this to 1000 (just like 
https://github.com/ansible-collections/hetzner.hcloud/blob/2589783e1925290876793420c675a5f33ef0d575/plugins/modules/hcloud_server.py#L734-L737
will solve the problem.
Code is tested by rebuilding a CPX31 using a 2GB snapshot.
```
Traceback (most recent call last):
File "/tmp/ansible_hcloud_server_payload_yww09ltp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 829, in rebuild_server …
```

Increase rebuild wait_until_finished() timeout

---

changelogs/fragments/inventory-private-network-info.yml
plugins/inventory/hcloud.py

This can be used in the `compose`, `groups` and `keyed_groups` settings to dynamically build the inventory.
It also makes it possible for the user to override the `ansible_host` in `compose`, based on whether or not the server has a public ipv4 address, with fallback to the address in a specific private network.
Closes #184 #185
Related to #178 
Part of a 3 PR series:
- #186
- #187 
- #188
Inventory Plugin
/

feat(inventory): add all private networks as variables [1/3]

---

changelogs/fragments/inventory-handle-invalid-connect-with.yml
plugins/inventory/hcloud.py

Currently if any of the servers in the inventory do not work with the selected `connect_with` mode, the script exits and returns 0 servers. This can happen for example if one of your servers does not have a public ipv4 address, but you set `connect_with: public_ipv4` (default).
This commit changes the behaviour to log a warning message, and just skip setting `ansible_host` for this server. This server will not be reachable by ansible by default, but users can use `compose` to override the `ansible_host` that we set based on the other variables.
Related to #178
Rebased on #186
Part of a 3 PR series:
- #186
- #187 
- #188
Inventory Plugin
/

feat(inventory): handle servers that dont work with connect_with setting [2/3]

---

changelogs/fragments/inventory-ipv6-adress-variable.yml
plugins/inventory/hcloud.py

This variable matches the `ansible_host` variable that we set when `connect_with: public_ipv6`, and allows the user to dynamically choose the connection method in `compose`.
Related to #178 
Rebased on #187 
Part of a 3 PR series:
- #186
- #187 
- #188
Inventory Plugin
/

feat(inventory): add variable for ipv6 address [3/3]

---

changelogs/fragments/server-race-condition-pg-attach.yml
plugins/modules/hcloud_server.py

In some cases the server was still marked as locked after attaching it to a placement_group. This caused potential follow up tasks that use the server to fail.
This happened because the action returned by `add_to_placement_group()` was not waited upon.
For the detach case this is handled correctly.
`hcloud_server` module
I noticed this because the integration test for `hcloud_placement_group` was failing in our internal CI.

fix(server): server still locked after placement_group attach

---

tests/integration/targets/hcloud_certificate/tasks/main.yml
tests/integration/targets/hcloud_datacenter_info/tasks/main.yml
tests/integration/targets/hcloud_floating_ip/defaults/main.yml
tests/integration/targets/hcloud_load_balancer_info/defaults/main.yml
tests/integration/targets/hcloud_load_balancer_target/defaults/main.yml
tests/integration/targets/hcloud_location_info/tasks/main.yml
tests/integration/targets/hcloud_placement_group/defaults/main.yml
tests/integration/targets/hcloud_placement_group/tasks/main.yml
tests/integration/targets/hcloud_primary_ip/defaults/main.yml
tests/integration/targets/hcloud_rdns/defaults/main.yml
tests/integration/targets/hcloud_server/defaults/main.yml
tests/integration/targets/hcloud_server_info/defaults/main.yml
tests/integration/targets/hcloud_server_network/defaults/main.yml
tests/integration/targets/hcloud_ssh_key/defaults/main.yml
tests/integration/targets/hcloud_volume/defaults/main.yml
tests/integration/targets/hcloud_volume_info/defaults/main.yml

Fix various issues in the integration tests that were failing (mostly in our internal CI). See individual commits for explanation of the issues.
Integration tests
I could not figure out where `hcloud_prefix` is set, otherwise I would prefer to truncate that variable instead of doing it in so many different locations.

test: various fixes for integration tests

---

plugins/module_utils/hcloud.py
plugins/modules/hcloud_certificate.py
plugins/modules/hcloud_certificate_info.py
plugins/modules/hcloud_datacenter_info.py
plugins/modules/hcloud_floating_ip.py
plugins/modules/hcloud_floating_ip_info.py
plugins/modules/hcloud_image_info.py
plugins/modules/hcloud_load_balancer.py
plugins/modules/hcloud_load_balancer_info.py
plugins/modules/hcloud_load_balancer_network.py
plugins/modules/hcloud_load_balancer_service.py
plugins/modules/hcloud_load_balancer_target.py
plugins/modules/hcloud_load_balancer_type_info.py
plugins/modules/hcloud_location_info.py
plugins/modules/hcloud_network.py
plugins/modules/hcloud_network_info.py
plugins/modules/hcloud_primary_ip.py
plugins/modules/hcloud_rdns.py
plugins/modules/hcloud_route.py
plugins/modules/hcloud_server.py
plugins/modules/hcloud_server_info.py
plugins/modules/hcloud_server_type_info.py
plugins/modules/hcloud_ssh_key.py
plugins/modules/hcloud_ssh_key_info.py
plugins/modules/hcloud_subnetwork.py
plugins/modules/hcloud_volume.py
plugins/modules/hcloud_volume_info.py

The linting rule `unused-import` was recently activated in ansible-test.
This commit removes all unused imports to satify the linting rule.
- 
See ansible-collections/news-for-maintainers#34

lint: fix unused-import errors

---

changelogs/fragments/server-fix-backups.yml
plugins/modules/hcloud_server.py
tests/integration/targets/hcloud_server/tasks/basic.yml
tests/integration/targets/hcloud_server/tasks/main.yml

With an existing server with backups enabled and the state being either present, started, stopped, restarted or rebuild and the backups module parameter not set, the module would disable backups and in turn delete all existing backups.
The correct behaviour (leave backups untouched when parameter not set) is implemented by this commit. Strong typing would have prevented this.
`hetzner.hcloud.hcloud_server`
```paste below
```

fix(server): prevent backups from being disabled when undefined

---

tests/integration/targets/hcloud_server/tasks/private_network_only.yml

The server that was being handled could still exist from previous tests running in the same suite. This can be fixed by making sure that the server does not exist at the start of this test suite.
Related to #203
- Test Pull Request
`hcloud_server`
Example logs from [failed CI pipeline](https://dev.azure.com/ansible/hetzner.hcloud/_build/results?buildId=72745&view=logs&j=d01ff689-4e85-566d-4792-f9984acde0cb&t=38074baf-391d-5150-7bd1-d2de1d57686f&l=1589):
```paste below
06:28 TASK [hcloud_server : test create server with primary network and no internet] ***
06:29 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'hcloud.hcloud.APIException'>, Server must be offline when unassigning a Primary IP
06:29 …
```

test: flaky test for hcloud_server private_network_only

---

.azure-pipelines/azure-pipelines.yml
.gitlab-ci.yml
tests/sanity/ignore-2.16.txt

- Add tests for Ansible 2.15
- Add sanity ignore file for 2.16, as thats used by devel now
- Configure azure pipelines to also run group 3 of the integration tests
Related to https://github.com/ansible-collections/news-for-maintainers/issues/41

ci: add tests for ansible 2.15

---

plugins/modules/hcloud_server.py

Make sure that we only log the deprecation warning if force_upgrade was actually set. Right now it also logs because a default value for the field is set.
Closes #201
- `hcloud_server`

fix(server): only show force_upgrade warning if actually set

---

plugins/modules/hcloud_image_info.py

Shows a warning when using `image_info` to get an image by name but without specifying an architecture. @LKaemmerling already requested this for the initial PR #208, but there was no time to get it implemented back then.
This behaviour is equivalent to the cli:
```
➜ hcloud image describe ubuntu-22.04
INFO: This command only returns x86 images by default. Explicitly set the --architecture=x86|arm flag to hide this message.
ID:             67794396
[cut]
➜ hcloud image describe ubuntu-22.04 --architecture x86
ID:             67794396
[cut]
```
- `hcloud_image_info`

docs: show warning if image_info is used without architecture

---

changelogs/fragments/server_error_deprecated_image.yml
plugins/modules/hcloud_server.py

When using a deprecated image with the `allow_deprecated_image` flag, the script would crash because the string interpolation was not done correctly. The parentheses were in the wrong place.
Error would look like this:
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/julian/.ansible/tmp/ansible-tmp-1686564668.6136558-165294-192879183382787/AnsiballZ_hcloud_server.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/julian/.ansible/tmp/ansible-tmp-1686564668.6136558-165294-192879183382787/AnsiballZ_hcloud_server.py\", line 99, in …

fix(server): TypeError when using deprecated image

---

plugins/modules/hcloud_image_info.py
plugins/modules/hcloud_server.py
tests/integration/targets/hcloud_floating_ip/tasks/main.yml
tests/integration/targets/hcloud_load_balancer_info/tasks/main.yml
tests/integration/targets/hcloud_load_balancer_target/tasks/main.yml
tests/integration/targets/hcloud_placement_group/tasks/main.yml
tests/integration/targets/hcloud_server/tasks/basic.yml
tests/integration/targets/hcloud_server/tasks/firewalls.yml
tests/integration/targets/hcloud_server/tasks/primary_ips.yml
tests/integration/targets/hcloud_server/tasks/private_network_only.yml
tests/integration/targets/hcloud_server/tasks/validation.yml
tests/integration/targets/hcloud_server_network/tasks/main.yml
tests/integration/targets/hcloud_ssh_key/tasks/main.yml
tests/integration/targets/hcloud_volume/tasks/main.yml

Update all references to ubuntu-18.04 (and 20.04) to 22.04, as ubuntu 18.04 is EOL and deprecated in Hetzner Cloud. This causes a CI failure in the main branch:
https://dev.azure.com/ansible/hetzner.hcloud/_build/results?buildId=80941&view=logs&j=fdb818b8-39d8-529a-d9da-324e304604bc&t=2d52cce2-88ce-5057-da88-145e92cee00f&l=1094
- CI
CI Jobs fail with:
```
You try to use a deprecated image. The image ubuntu-18.04 will continue to be available until 2023-08-29. If you want to use this image use allow_deprecated_image=yes.
```

ci: ubuntu-18.04 is deprecated/EOL

---

README.md

Similarly to https://github.com/ansible-collections/amazon.aws#python-version-compatibility, add note about the python compatibility for the collection.
https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#python-requirements
- Docs

docs: add note about python compatibility

---

tests/requirements.yml

ansible-lint seem to complain about the yaml key used, if we want to have those requirements only for the integration tests, we should probably move the requirements.yml file inside the test/integrations folder.

test: fix ansible-tests requirements file

---

.azure-pipelines/azure-pipelines.yml

This upgrade the base test container used in the Azure pipelines.

ci: upgrade ansible/azure-pipelines-test-container to v4.0.1

---

.gitlab-ci.yml

The CI pipeline is not running because of a missing tag.
I am moving the default GitLab pipeline config (job tags, job templates) to a shared repository.
Bumping the version of python to match the one used inside the azure pipeline testing container.

ci: fix gitlab pipeline not running 

---

.azure-pipelines/azure-pipelines.yml
.github/workflows/lint.yml
README.md

Now that the main branch is used to for the coming 2.x releases, the `stable-1` branch is used to allow any additional 1.x release.
This PR enables CI for the `stable-1` branch.

chore: setup the `stable-1` release branch

---

renovate.json

Add a basic Renovate configuration file and instruct Renovate to upgrade the version of hcloud when a new version is available.
Related to #244
Renovate is not enabled on this repository, this PR is only relevant if we can run Renovate against this repository, either using the Github App or from an external setup.
Here is how it looks like: https://github.com/jooola/hetzner.hcloud/pull/1

chore: add renovate regex manager for hcloud upgrades

---

.pre-commit-config.yaml
README.md
changelogs/fragments/drop-support-for-python-3.7.yml
tests/config.yml

Drop support for python 3.7, this is a preparation work to be able to land https://github.com/hetznercloud/hcloud-python/pull/242.

feat!: drop support for python3.7

---

tests/integration/targets/hcloud_floating_ip/aliases
tests/integration/targets/hcloud_floating_ip_info/aliases
tests/integration/targets/hcloud_location_info/aliases
tests/integration/targets/hcloud_primary_ip/aliases
tests/integration/targets/hcloud_primary_ip_info/aliases
tests/integration/targets/hcloud_server/aliases

Move some tests in the group3 to balance test duration.
One large test is the `hcloud_server` module, it was moved from the group1 to the group3.
Before:
```
10 shippable/hcloud/group1
19 shippable/hcloud/group2
2 shippable/hcloud/group3
```
After:
```
9 shippable/hcloud/group1
14 shippable/hcloud/group2
8 shippable/hcloud/group3
```

test: reorganize groups to balance test duration

---

changelogs/fragments/do-not-set-inventory-server-image-variables-when-undefined.yml
plugins/inventory/hcloud.py

Related to #116
Don't set "No Image * found" string if the server image is not defined. This is not an intuitive behavior. 
This is a breaking change.
`inventory`

fix!: don't set inventory image vars if server image is undefined

---

.pre-commit-config.yaml

The antsibull-changelog pre-commit hooks are now present upstream. 
https://togithub.com/ansible-community/antsibull-changelog/pull/125

chore: use upstream antsibull-changelog pre-commit hooks

---

.pre-commit-config.yaml

The previous PR #277 merge somehow destroyed the config while rebasing and squashing.
https://github.com/ansible-collections/hetzner.hcloud/commit/1b83de57ef5f3f90ed615bf6fa200d333d9a4dd1

chore: fix pre-commit config

---

tests/integration/requirements.txt
tests/integration/targets/hcloud_certificate/tasks/cleanup.yml
tests/integration/targets/hcloud_certificate/tasks/test.yml
tests/integration/targets/hcloud_certificate_info/tasks/cleanup.yml
tests/integration/targets/hcloud_certificate_info/tasks/prepare.yml
tests/integration/targets/hcloud_certificate_info/tasks/test.yml
tests/integration/targets/setup_selfsigned_certificate/tasks/main.yml
tests/requirements.yml

- Improve the setup_selfsigned_certificate helper
- Use the community.crypto collection instead of handmade tasks.
- Implement the new testing framework (prepare.yml/cleanup.yml #239)

test: improve tests using setup_selfsigned_certificate helper

---

.gitlab-ci.yml

The test stage is missing and required by the imported CI templates.

ci: fix gitlab stages

---

.ansible-lint
changelogs/fragments/fix-error-on-location_info-invalid-id.yml
plugins/modules/hcloud_location_info.py
tests/integration/targets/hcloud_location_info/defaults/main/main.yml
tests/integration/targets/hcloud_location_info/tasks/test.yml

The location info module crashed when querying a location using an invalid ID
The "with wrong id" test was using the name parameter instead of the id parameter, so the test could not catch this.
We might find similar error in other modules.
hcloud_location_info

fix: do not error on location_info invalid id

---

changelogs/fragments/consistently-fail-on-invalid-id.yml
changelogs/fragments/fix-error-on-location_info-invalid-id.yml
plugins/modules/hcloud_certificate_info.py
plugins/modules/hcloud_datacenter_info.py
plugins/modules/hcloud_floating_ip_info.py
plugins/modules/hcloud_image_info.py
plugins/modules/hcloud_iso_info.py
plugins/modules/hcloud_load_balancer_info.py
plugins/modules/hcloud_load_balancer_type_info.py
plugins/modules/hcloud_location_info.py
plugins/modules/hcloud_network_info.py
plugins/modules/hcloud_primary_ip_info.py
plugins/modules/hcloud_server_info.py
plugins/modules/hcloud_server_type_info.py
plugins/modules/hcloud_ssh_key_info.py
plugins/modules/hcloud_volume_info.py
tests/integration/targets/hcloud_location_info/tasks/test.yml
tests/integration/targets/hcloud_network_info/tasks/test.yml
tests/integration/targets/hcloud_server_info/tasks/test.yml
tests/integration/targets/hcloud_volume_info/tasks/test.yml

Document and make sure we fail when querying an invalid ID.
Partially reverts #292
Fixes #298 
The missing tests will be implemented in #299
`*_info`

fix: consistently fail on invalid ID in `*_info` modules

---

README.md

Add Github version badge and Ansible Galaxy version. Fix the azure build status to target the main branch.
We can check that the Github and Ansible Galaxy version match by looking at the badges.

chore: update README badges

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/fix-string-formatting-error-on-deprecated-server-type-warning.yml
galaxy.yml
plugins/module_utils/version.py

Prepare v2.1.1 release.
This should also trigger a new publish process, since 2.1.0 never had the change to be published to ansible-galaxy.

chore: prepare v2.1.1

---

.gitlab-ci.yml

The pre-commit template does not set the job automatically.

ci: explicitly declare pre-commit job

---

tests/integration/targets/hcloud_certificate/defaults/main/main.yml
tests/integration/targets/hcloud_image_info/defaults/main/main.yml
tests/integration/targets/hcloud_image_info/meta/main.yml
tests/integration/targets/hcloud_image_info/tasks/cleanup.yml
tests/integration/targets/hcloud_image_info/tasks/prepare.yml
tests/integration/targets/hcloud_image_info/tasks/test.yml
tests/integration/targets/hcloud_load_balancer_target/defaults/main/main.yml
tests/integration/targets/hcloud_load_balancer_target/tasks/test.yml
tests/integration/targets/hcloud_subnetwork/defaults/main/main.yml
tests/integration/targets/setup_hcloud_cli/tasks/main.yml

Setup new temporary project service for integration tests.
- Use the hc-integrations-test.de domain for certificates creation
- Use new Hetzner account vSwitch
- Use new Hetzner account server IP
- Create snapshots during setup (instead of "always-there-snapshot")

test: setup new temporary project service for integration tests 

---

tests/integration/targets/hcloud_certificate/defaults/main.yml
tests/integration/targets/hcloud_image_info/defaults/main.yml
tests/integration/targets/hcloud_image_info/meta/main.yml
tests/integration/targets/hcloud_image_info/tasks/main.yml
tests/integration/targets/hcloud_load_balancer_target/defaults/main.yml
tests/integration/targets/hcloud_load_balancer_target/tasks/main.yml
tests/integration/targets/hcloud_subnetwork/defaults/main.yml
tests/integration/targets/setup_hcloud_cli/tasks/main.yml

Backport of https://github.com/ansible-collections/hetzner.hcloud/commit/62ab0570c85540991caafe6d3523aa8992d8f84e (https://github.com/ansible-collections/hetzner.hcloud/pull/316) to branch `stable-1`

test: setup new temporary project service for integration tests (stable-1)

---

.azure-pipelines/azure-pipelines.yml

Related to https://github.com/ansible-collections/news-for-maintainers/issues/58
And see https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix

ci: add ansible-core 2.16 to the test matrix

---

changelogs/fragments/rename-load-balancer-service-http-health-check-dict.yaml
plugins/modules/hcloud_load_balancer_service.py

In the `hcloud_load_balancer_service` return data, the `health_check.http.certificates` field must be named `health_check.http.status_codes`.
https://docs.hetzner.cloud/#load-balancers-get-a-load-balancer
Fixes #332 
hcloud_load_balancer_service

fix: invalid field in load_balancer_service health_check.http return data

---

changelogs/fragments/require-firewall-port-argument-on-tcp-or-udp-protocol.yaml
plugins/modules/hcloud_firewall.py

When managing a tcp/udp firewall rule, provide a clear error message when the port is missing from the rule.
Closes #344

fix: firewall port argument is required with udp or tcp

---

README.md

Fix ansible galaxy badge urls. See https://www.ansible.com/blog/new-ansible-galaxy

chore: new galaxy api broke the version shield

---

.github/workflows/release-please.yml
changelogs/dev-changelog.md

The version tag regex allowing to publish to ansible-galaxy does not allow versions to be prefixed with a v: 
https://github.com/ansible/zuul-config/blob/468493fef435a6152d982fc7c41fe2ff2066e139/zuul.d/pipelines.yaml#L146-L155
Introducing the v prefix is also breaking with the previous tag naming convention.

build: don't include v prefix in version tags

---

Makefile

Missing venv when running lint-docs from a clean repo.

chore: add venv dependency to lint-docs target

---

changelogs/fragments/add-deprecation-field-to-iso-info.yaml
plugins/modules/hcloud_iso_info.py
tests/integration/targets/hcloud_iso_info/defaults/main/main.yml
tests/integration/targets/hcloud_iso_info/tasks/test.yml

See these changelog entries for the announcement:
- https://docs.hetzner.cloud/changelog#2023-10-12-deprecation-info-for-isos
- https://docs.hetzner.cloud/changelog#2023-10-12-field-deprecated-on-isos-is-now-deprecated
hcloud_iso_info

feat: add deprecation field to hcloud_iso_info

---

.ansible-lint
tests/integration/targets/hcloud_subnetwork/defaults/main/main.yml
tests/integration/targets/hcloud_subnetwork/tasks/cleanup.yml
tests/integration/targets/hcloud_subnetwork/tasks/prepare.yml
tests/integration/targets/hcloud_subnetwork/tasks/test.yml
tests/utils/ci.sh
tests/utils/gitlab/gitlab.sh

The vswitch subnet validation changed: the subnet ip_range must be smaller than the network ip_range **AND** must not start with the same IP.
See https://github.com/ansible-collections/hetzner.hcloud/runs/17672011247
In addition, I reworked the tests to use the new testing framework.

test: fix vswitch subnets ip_range

---

README.md

Use the new API to have up-to-date versions badge.

chore: update galaxy version badge url

---

.azure-pipelines/azure-pipelines.yml
.github/workflows/release-please.yml

Disable azure pipelines for draft pull requests and ask release-please to create draft pull requests. This should reduce the amount of CI usage around the release please workflow.

ci: reduce usage when pushing release-please updates

---

changelogs/fragments/allow-selecting-a-resource-using-its-id.yaml
plugins/module_utils/hcloud.py
plugins/modules/hcloud_load_balancer_network.py
plugins/modules/hcloud_load_balancer_service.py
plugins/modules/hcloud_load_balancer_target.py
plugins/modules/hcloud_rdns.py
plugins/modules/hcloud_route.py
plugins/modules/hcloud_server_network.py
plugins/modules/hcloud_subnetwork.py
tests/integration/targets/hcloud_load_balancer_network/tasks/test.yml
tests/integration/targets/hcloud_load_balancer_service/tasks/test.yml
tests/integration/targets/hcloud_load_balancer_target/tasks/test.yml
tests/integration/targets/hcloud_rdns/tasks/test.yml

Allow referring to resources using their IDs for:
- hcloud_load_balancer_network
- hcloud_load_balancer_service
- hcloud_load_balancer_target
- hcloud_rdns
- hcloud_route
- hcloud_server_network
- hcloud_subnetwork
- hcloud_load_balancer_network
- hcloud_load_balancer_service
- hcloud_load_balancer_target
- hcloud_rdns
- hcloud_route
- hcloud_server_network
- hcloud_subnetwork

feat: allow selecting a resource using its ID

---

.github/workflows/release-please.yml

pre-commit.ci automatically pushes styling commit to the release please branch and might render the checkout in CI out of sync with the origin. This makes sure the release-please workflow does not fail by force pushing to the branch.

ci: force push antsibull-changelog changes

---

plugins/modules/hcloud_iso_info.py

The deprecated field is deprecated, we must use the deprecation object instead.
hcloud_iso_info

refactor: don't use ISO deprecated field

---

.github/workflows/lint.yml
.github/workflows/release-please.yml
.github/workflows/vendor.yml

This is an attempt to fix the linting job: https://github.com/ansible-collections/hetzner.hcloud/actions/runs/6692855477/job/18182866932
Run on python 3.11 until the following ticket is solved: https://github.com/aio-libs/aiohttp/issues/7675

ci: pin python version to 3.11

---

changelogs/fragments/add-server_types-to-datacenter-info.yaml
plugins/modules/hcloud_datacenter_info.py

Closes #204 
Return the `server_types` dict when querying the datacenters.
hcloud_datacenter_info

feat: add server_types to datacenter info module

---

changelogs/fragments/add_created_to_server_info.yaml
plugins/modules/hcloud_server.py
plugins/modules/hcloud_server_info.py

Add missing "created" field to ansible result
based on documentation https://docs.hetzner.cloud/#servers-get-all-servers
```
created
string required
Point in time when the Resource was created (in ISO-8601 format)
```
hcloud_server_info
hcloud_server

feat: add `created` field to server and server_info modules

---

.pre-commit-config.yaml

pre-commit autofixes at slowing down the release process. Let's ignore the format of the changelog files.

chore: don't format changelogs files

---

plugins/inventory/hcloud.py
plugins/modules/hcloud_floating_ip.py
plugins/modules/hcloud_load_balancer.py
plugins/modules/hcloud_load_balancer_network.py
plugins/modules/hcloud_load_balancer_service.py
plugins/modules/hcloud_load_balancer_target.py
plugins/modules/hcloud_network.py
plugins/modules/hcloud_placement_group.py
plugins/modules/hcloud_primary_ip.py
plugins/modules/hcloud_rdns.py
plugins/modules/hcloud_route.py
plugins/modules/hcloud_server_network.py
plugins/modules/hcloud_subnetwork.py

Since we vendored the hcloud-python library, those requirements are not needed anymore.

docs: remove hcloud-python requirements from modules

---

docs/docsite/extra-docs.yml
docs/docsite/links.yml
docs/docsite/rst/authentification.rst

Add a global documentation for the collection. See the https://github.com/ansible-collections/collection_template and https://github.com/ansible-collections/amazon.aws/tree/main/docs/docsite for examples.

docs: add global docs using docsite

---

changelogs/fragments/improve-modules-api-arguments.yml
plugins/doc_fragments/hcloud.py
plugins/module_utils/hcloud.py
tests/unit/module_utils/test_hcloud.py

Make the api endpoint module argument consistent with the api token. 
- Renamed the `endpoint` module argument to `api_endpoint`, backward compatibility is maintained using an alias.
- Allow to configure it using the `HCLOUD_ENDPOINT` env var.
This makes the inventory config and the modules config a bit more consistent.

feat: rename api_endpoint module argument

---

.ansible-lint
changelogs/fragments/add-module-defaults-group-for-all-modules.yml
docs/docsite/rst/authentification.rst
examples/use-module-defaults-group.yml
meta/runtime.yml

This allows to use `module_defaults` against all the modules at once using the new `hetzner.hcloud.all` `action_group`.
You can now pass the `api_token` argument using module_defaults:
```yaml
- name: Demonstrate the usage of the 'hetzner.hcloud.all' module_defaults group
hosts: localhost
connection: local
module_defaults:
group/hetzner.hcloud.all:
api_token: "{{ _vault_hcloud_api_token }}"
tasks:
- name: Create a volume
hetzner.hcloud.volume:
name: my-volume
location: fsn1
size: 100
state: present
register: volume
```   
See the documentation and examples for more details.

feat: add `hetzner.hcloud.all` action group

---

changelogs/fragments/improve-inventory-api-options.yml
plugins/inventory/hcloud.py

- Rename the inventory `token` option to `api_token`, use aliases for backward compatibility.
- Rename the inventory `token_env` option to `api_token_env`, use aliases for backward compatibility.
- Deprecate the inventory `api_token_env` option, suggest using a lookup plugin (`{{ lookup('ansible.builtin.env', 'YOUR_ENV_VAR') }}`) or use the well-known `HCLOUD_TOKEN` environment variable name.
- Let ansible parse the options, remove homemade options parsing.
- Improve and document the existing `api_endpoint` option.
hcloud inventory

feat(inventory): improve api options

---

Makefile

This helps to run sanity/units/integrations tests locally.

chore: add makefile ansible-test targets

---

plugins/inventory/hcloud.py
plugins/module_utils/client.py
plugins/module_utils/hcloud.py

Extract some client utils functions in reusable function, to be used in the inventory plugin.

refactor: extract client utils in reusable functions

---

.ansible-lint
changelogs/fragments/fix-inventory-fresh-cache.yaml
examples/use-refresh-inventory.yml
plugins/module_utils/client.py

The class scoped `cache` dict was being shared across all `cached_session`, we now make sure that the cache is instance scoped.
Fixes #403

fix(inventory): always use fresh cache on new cached session

---

.ansible-lint
examples/server-with-private-ip-only.yml

Add an example to show how to create servers that only have private IPs.

docs: create servers with private ips only

---

changelogs/fragments/replace-deprecated-ansible.netcommon-with-python-ipaddress.yml
galaxy.yml
plugins/modules/rdns.py
tests/integration/targets/rdns/tasks/test.yml
tests/requirements.yml

Replace `ansible.netcommon` deprecated ipaddr utils with python `ipaddress` module. The  `ansible.netcommon` collection is no longer required by the collections. We still use the `ansible.utils` collections for testing

feat: replace `ansible.netcommon` utils with python3 `ipaddress` module

---

tests/integration/targets/certificate/tasks/test.yml
tests/integration/targets/certificate_info/tasks/test.yml
tests/integration/targets/firewall/tasks/test.yml
tests/integration/targets/floating_ip/tasks/test.yml
tests/integration/targets/floating_ip_info/tasks/test.yml
tests/integration/targets/image_info/tasks/test.yml
tests/integration/targets/iso_info/tasks/test.yml
tests/integration/targets/load_balancer/tasks/test.yml
tests/integration/targets/load_balancer_info/tasks/test.yml
tests/integration/targets/network/tasks/test.yml
tests/integration/targets/network_info/tasks/test.yml
tests/integration/targets/placement_group/tasks/test.yml
tests/integration/targets/primary_ip_info/tasks/test.yml
tests/integration/targets/rdns/tasks/test.yml
tests/integration/targets/route/tasks/test.yml
tests/integration/targets/server/tasks/test_basic.yml
tests/integration/targets/server_info/tasks/test.yml
tests/integration/targets/ssh_key/tasks/test.yml
tests/integration/targets/ssh_key_info/tasks/test.yml
tests/integration/targets/subnetwork/tasks/test.yml
tests/integration/targets/volume/tasks/test.yml
tests/integration/targets/volume_info/tasks/test.yml

Attempt to fix the unsafe condition by removing unnecessary jinja templates.
Example of failing CI: https://dev.azure.com/ansible/hetzner.hcloud/_build/results?buildId=98486&view=logs&j=86ea7956-35b6-5577-ed45-fe20f8c6b276&t=a2e51dbe-b8d9-5c65-a584-138300c332b7&l=2562

test: remove jinja templates where unnecessary

---

.ansible-lint
tests/integration/targets/setup_selfsigned_certificate/tasks/main.yml
tests/integration/targets/setup_ssh_keypair/tasks/main.yml

Fix ansible lint error for the integrations setup roles.

test: fix linting error for integrations setup roles

---

.ansible-lint
tests/integration/targets/firewall/tasks/cleanup.yml
tests/integration/targets/firewall/tasks/test.yml

Use the new testing framework for the firewall integration tests and fix linting errors.

test: use testing framework for firewall integration tests

---

changelogs/fragments/add-inventory-hostvars-prefix-and-suffix-option.yml
plugins/inventory/hcloud.py

Add `hostvars_prefix` and `hostvars_suffix` options to customize the inventory host variables keys.
For example, with `hostvars_prefix: hcloud_ `, the host vars will be stored as follows:
```json
{
"_meta": {
"hostvars": {
"tmp": {
"ansible_host": "65.109.169.27",
"hcloud_architecture": "x86",
"hcloud_datacenter": "hel1-dc2",
"hcloud_id": 40573407,
"hcloud_image_id": 114690387,
"hcloud_image_name": "debian-12",
"hcloud_image_os_flavor": "debian",
"hcloud_ipv4": "65.109.169.27",
"hcloud_ipv6_network_mask": "64",
"hcloud_ipv6_network": "2a01:4f9:c012:4377::",
"hcloud_ipv6": "2a01:4f9:c012:4377::1",
"hcloud_labels": {},
"hcloud_location": "hel1",
"hcloud_name": "tmp",
"hcloud_private_networks": [],
"hcloud_server_type": "cx11",
"hcloud_status": "running",
"hcloud_type": "cx11"
}
}
}
}
``` …

feat: add `hostvars_prefix` and `hostvars_suffix` options to inventory hostvars

---

plugins/module_utils/hcloud.py

Fixes type checking (false unbound variables), for the fail json helper function that never returns (system exit).

refactor: add no return typings

---

Makefile

This should catch more RST errors.

chore: enable docs rstcheck

---

.azure-pipelines/azure-pipelines.yml

For each job, we use the oldest python version supported for the given ansible-core version. Now, for the ansible-core devel version, we use the most recent version of python supported.
This ensure that we are compatible with all python version.

ci: use latest python version for ansible devel jobs

---

changelogs/fragments/fix-firewall-deletion.yml
plugins/modules/firewall.py
tests/integration/targets/firewall/defaults/main/main.yml
tests/integration/targets/firewall/tasks/cleanup.yml
tests/integration/targets/firewall/tasks/prepare.yml
tests/integration/targets/firewall/tasks/test.yml

- Do not silence 'firewall still in use' deletions errors.
- Allow forcing the deletion of a firewall that is still in use.
Fixes #380
firewall

feat: allow forcing the deletion of firewalls that are still in use

---

changelogs/fragments/allow-renaming-networks.yml
plugins/modules/network.py

The network could not be renamed before. This was discovered while working on #448 
network

fix: allow renaming networks

---

changelogs/fragments/fix-load-balancer-cookie-lifetime.yml
plugins/modules/load_balancer_info.py
plugins/modules/load_balancer_service.py

The load balancer cookie lifetime field now returns the cookie lifetime value, instead of the cookie name.
load_balancer_info
load_balancer_service

fix: load balancer invalid cookie lifetime value returned

---

changelogs/fragments/remove-inventory-api_token_env-option.yml
plugins/inventory/hcloud.py

Remove the previously deprecated `api_token_env` to fully leverage the ansible inventory options loader.
inventory

feat!: remove inventory `api_token_env` option

---

changelogs/fragments/fix-always-return-iso-8601-formatted-datetime.yml
plugins/modules/certificate.py
plugins/modules/certificate_info.py
plugins/modules/iso_info.py

Fixes #91
Always return datetime as iso-8601 formatted strings.

fix!: always return iso-8601 formatted date time

---

changelogs/fragments/add-inventory-hostname-option.yml
plugins/inventory/hcloud.py

Adds a `hostname` option that allow the user to pass a template to add a prefix or use the hostvars to build the hostname.
For example:
```yml
plugin: hetzner.hcloud.hcloud
hostname: "hcloud-{{ location }}-{{ name }}"
```
OR with a hostvars_prefix:
```yml
plugin: hetzner.hcloud.hcloud
hostvars_prefix: hcloud_
hostname: "hcloud-{{ hcloud_location }}-{{ hcloud_name }}"
```
Fixes #115
inventory

feat(inventory): allow templating instances hostname

---

Makefile
tests/integration/cloud-config-hcloud.ini.in

Adds a helper to configure the dev env. For example reexporting a hcloud_token and reload the integration tests configuration:
```bash
export HCLOUD_TOKEN="$(get-tmp-hcloud-token)"
make dev
```

chore: add dev target helper

---

.ansible-lint
changelogs/fragments/sort-alias-ips-in-server-network.yml
plugins/modules/server_network.py
tests/integration/targets/server_network/aliases
tests/integration/targets/server_network/tasks/cleanup.yml
tests/integration/targets/server_network/tasks/prepare.yml
tests/integration/targets/server_network/tasks/test.yml

- test: use testing framework for server_network integration tests
- fix: return sorted alias_ips in server_network module
server_network

fix: return sorted `alias_ips` in `server_network` module

---

tests/integration/targets/floating_ip/tasks/test.yml
tests/integration/targets/load_balancer_info/tasks/prepare.yml
tests/integration/targets/load_balancer_target/tasks/test.yml
tests/integration/targets/server_info/tasks/prepare.yml
tests/integration/targets/volume/tasks/test.yml

Reduce test time by not starting servers when not required.

test: do not start server where possible

---

tests/integration/targets/primary_ip/tasks/cleanup.yml
tests/integration/targets/primary_ip/tasks/test.yml

Use the new testing framework for the primary ip integration tests.

test: improve primary_ip integration using the testing framework

---

pyproject.toml

Disable some pylint rules that are out of scope for the time being, to stop polluting the pylint errors report. Those might be re-enabled at a later stage.

chore: disable out of scope pylint rules

---

tests/integration/targets/firewall/tasks/cleanup.yml
tests/integration/targets/firewall_info/tasks/cleanup.yml
tests/integration/targets/firewall_resource/tasks/cleanup.yml

Cleanup the firewall before the server to prevent a server deletion timeout.

test: force firewall cleanup before running server cleanup

---

changelogs/fragments/server-rename-image_allow_deprecated-argument.yml
plugins/modules/server.py

Renamed the `allow_deprecated_image` to `image_allow_deprecated` argument to ensure the `image` related options use the same namespace.
This is backward compatible, as we introduce a new alias for the old option name.

feat: rename server `image_allow_deprecated` option

---

changelogs/fragments/server-empty-string-arguments.yml
tests/integration/targets/placement_group/tasks/test.yml

- Do not remove the server from its placement group when the `placement_group` argument is not specified.
- Pass an empty string to the `placement_group` argument to remove a server from its placement group.

fix: use empty string to remove server from its placement group

---

plugins/modules/certificate.py
plugins/modules/floating_ip.py
plugins/modules/load_balancer.py
plugins/modules/load_balancer_network.py
plugins/modules/load_balancer_service.py
plugins/modules/load_balancer_target.py
plugins/modules/network.py
plugins/modules/primary_ip.py
plugins/modules/rdns.py
plugins/modules/route.py
plugins/modules/server.py
plugins/modules/server_network.py
plugins/modules/subnetwork.py
plugins/modules/volume.py

Some action waiting time have been set to an arbitrary number, which could force the users to wait for too long, while we could have raised a timeout.
This changes the arbitrary numbers with rough estimate based on the average actions time and some leeway.

fix: improve actions waiting timeout based on data

---

.azure-pipelines/azure-pipelines.yml

See https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
Also bump the test containers to version v6.0.0.

ci: add ansible-core 2.17 to the test matrix

---

tests/integration/targets/primary_ip/tasks/test.yml

When the following steps are executed, the server deletion fails with a timeout:
- delete primary IP (attached to the server)
- delete server
- timeout after 5 minutes on server delete action
Adding the 2 seconds pause will work around this timeout.

test: add workaround to prevent a timeout during the server deletion

---

docs/docsite/rst/guides.rst
examples/server-with-firewall.yml
examples/server-with-private-ip-only.yml
examples/use-module-defaults-group.yml
examples/use-refresh-inventory.yml
plugins/inventory/hcloud.py
plugins/modules/load_balancer.py
plugins/modules/load_balancer_info.py
plugins/modules/network_info.py
plugins/modules/server.py
plugins/modules/server_info.py
tests/integration/targets/firewall/tasks/prepare.yml
tests/integration/targets/firewall_info/tasks/prepare.yml
tests/integration/targets/firewall_resource/tasks/prepare.yml
tests/integration/targets/floating_ip/tasks/test.yml
tests/integration/targets/image_info/tasks/prepare.yml
tests/integration/targets/load_balancer_info/tasks/prepare.yml
tests/integration/targets/load_balancer_target/tasks/test.yml
tests/integration/targets/primary_ip/tasks/prepare.yml
tests/integration/targets/rdns/tasks/prepare.yml
tests/integration/targets/server/tasks/test_basic.yml
tests/integration/targets/server/tasks/test_validation.yml
tests/integration/targets/server_info/tasks/prepare.yml
tests/integration/targets/server_network/tasks/prepare.yml
tests/integration/targets/server_type_info/defaults/main/main.yml
tests/integration/targets/server_type_info/tasks/test.yml
tests/integration/targets/ssh_key/tasks/test.yml
tests/integration/targets/volume/tasks/test.yml

Learn more: https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-shared-intel-vcpus-are-deprecated
- Updated docs with newer server types
- Use ARM server type for tests

chore: replace deprecated server type with cx22

---

changelogs/fragments/keep-deprecated-alias.yml
plugins/modules/server.py

This was not removed during the v4.0.0 release, we must therefor reschedule it for the v5.0.0 release.

fix: keep deprecated alias for another major version

---

tests/integration/targets/placement_group/tasks/test.yml
tests/integration/targets/server/tasks/test_basic.yml
tests/integration/targets/server/tasks/test_firewalls.yml
tests/integration/targets/server/tasks/test_primary_ips.yml
tests/integration/targets/server/tasks/test_private_network_only.yml

Ensure we are consistent across our tests, and updates some server types that were missing from the previous PR updating this:
https://github.com/ansible-collections/hetzner.hcloud/pull/510

test: update server type to cax11

---

tests/integration/targets/subnetwork/defaults/main/main.yml

Adds a few vSwitche IDs from our internal Hetzner Account, to run test manually.

test: add internal account vswitch ids

---

examples/server-assign-to-subnetwork.yml

Adds an example that shows how to assign a server to a specific subnetwork.

docs: add example to assign server to a specific subnet

---

changelogs/fragments/exponential-actions-polling-interval.yml
plugins/module_utils/client.py
plugins/module_utils/hcloud.py
plugins/modules/certificate.py
plugins/modules/server.py
tests/unit/module_utils/test_client.py

Replace the constant poll interval of 1 second, with a truncated exponential back off algorithm with jitter.
Below is a suite of poll interval (in seconds) generated by the new algorithm:
```
1.49
2.14
5.46
6.51
6.57
5.57
5.98
7.13
6.59
7.10
5.54
5.03
6.56
5.96
6.72
7.21
7.05
5.31
5.60
6.33
6.82
5.42
6.08
6.60
TOTAL: 140.77
```

feat: use exponential backoff algorithm when polling actions

---

changelogs/fragments/deprecate-server-type-pricing.yml
plugins/modules/server_type_info.py

There will be a breaking change in the API regarding Traffic Prices and Server Type Included Traffic on 2024-08-05. This release marks the affected fields as `Deprecated`. Please check if this affects any of your code and switch to the replacement fields where necessary.
You can learn more about this change in [our changelog](https://docs.hetzner.cloud/changelog#2024-07-25-cloud-api-returns-traffic-information-in-different-format).

feat: deprecate `server_type_info` `included_traffic` return value

---

tests/integration/targets/firewall/tasks/cleanup.yml
tests/integration/targets/firewall_info/tasks/cleanup.yml
tests/integration/targets/firewall_resource/tasks/cleanup.yml

Prevent a timeout error when cleaning up server right after the firewall got deleted.

test: add server cleanup timeout workaround

---

tests/integration/targets/firewall/tasks/prepare.yml
tests/integration/targets/firewall_info/tasks/prepare.yml
tests/integration/targets/firewall_resource/tasks/prepare.yml
tests/integration/targets/floating_ip/tasks/test.yml
tests/integration/targets/image_info/tasks/prepare.yml
tests/integration/targets/load_balancer_info/tasks/prepare.yml
tests/integration/targets/load_balancer_target/tasks/test.yml
tests/integration/targets/primary_ip/tasks/prepare.yml
tests/integration/targets/rdns/tasks/prepare.yml
tests/integration/targets/server/tasks/test_basic.yml
tests/integration/targets/server_info/tasks/prepare.yml
tests/integration/targets/server_network/tasks/prepare.yml
tests/integration/targets/ssh_key/tasks/test.yml

Make sure that the tests uses the `hcloud_location_name` variable for the tests.

test: ensure location is used for tests

---

.ansible-lint
tests/integration/targets/load_balancer_service/tasks/cleanup.yml
tests/integration/targets/load_balancer_service/tasks/prepare.yml
tests/integration/targets/load_balancer_service/tasks/test.yml

SUMMARY
Use the new testing framework for the load_balancer_service integration tests.
Depends on #545

test: improve `load_balancer_service` integration using new framework

---

.ansible-lint
tests/integration/targets/load_balancer_target/tasks/cleanup.yml
tests/integration/targets/load_balancer_target/tasks/prepare.yml
tests/integration/targets/load_balancer_target/tasks/test.yml

Use the new testing framework for the load_balancer_target integration tests.
Depends on #546

test: improve `load_balancer_target` integration using new framework

---

README.md

Dear maintainers,
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README. Similar PRs are being raised across all included collections under the ansible-collection org for now.
- If you have your forum group and/or tags related to the collection, please update corresponding lines by suggesting changes to the PR.
- If the collection is not present on the Ansible forum yet, please check out the existing [tags](https://forum.ansible.com/tags) and [groups](https://forum.ansible.com/g) - use what suits your collection. If there is no appropriate tag, please [request …

docs: add communication section with forum information

---

plugins/modules/firewall_resource.py

In the example, we should use `firewall` instead of `name` as per the options described at the top of the documentation.
I had an error on my VSCode when I used `name` as it was showing in the example. Looking at the documentation, it says I should be using `firewall` instead. 
I haven't explicitly tested to see if it would have failed, but I thought replacing `name` with `firewall` was the right thing to do, as it works fine like this.
firewall_resource
```paste below
```

docs: fix `firewall_resource` examples input parameters

---

changelogs/fragments/server-create-next-actions.yml
plugins/modules/server.py

While we wait a long time on the `create_server` actions, we only wait 2 minutes on any follow up actions like `start_server` or `attach_network`. This is sometimes not enough. This PR adds a longer wait timeout for the `next_actions` returned after creating the server.
- `hcloud.server` module
PR originally by @mmontesi
Replaces #558

fix(server): timeout in server creation when waiting on next actions

---

tests/integration/targets/iso_info/defaults/main/main.yml

The iso used for the tests is now deprecated, changed to the latest version of the system rescue iso.

test: do not use deprecated iso

---

changelogs/fragments/improve-unkown-certificate-error.yml
plugins/modules/load_balancer_service.py
tests/integration/targets/load_balancer_service/tasks/test.yml

Closes #563 
load_balancer_service

fix: improve unknown certificate error in `load_balancer_service`

---

.azure-pipelines/azure-pipelines.yml

See https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix

ci: add ansible-core 2.18 to the test matrix

---

.ansible-lint

Enable the ansible-lint unsupported-version lint rule.

test: enable unsupported-version lint rule

---

tests/integration/targets/firewall/tasks/test.yml
tests/integration/targets/firewall_resource/tasks/test.yml
tests/integration/targets/load_balancer_network/tasks/test.yml
tests/integration/targets/load_balancer_service/tasks/test.yml
tests/integration/targets/load_balancer_target/tasks/test.yml
tests/integration/targets/rdns/tasks/test.yml
tests/integration/targets/server_network/tasks/test.yml
tests/integration/targets/subnetwork/tasks/test.yml

We are testing that the parameters are missing, so we should ignore the linting errors.

test: ignore lint error for missing args in tests

---

plugins/modules/load_balancer_service.py

We only was to perform an update call when a value changed, or we end up with an empty update request.

fix: only update load balancer service when changed

---

.pre-commit-config.yaml

Ansible lint has a rule to check for missing required parameter. This ensure the `api_token` parameter is always set.

test: ensure ansible-lint do not fail for missing api_token

---

changelogs/fragments/server-add-created-state.yml
examples/server-with-private-ip-only.yml
plugins/modules/server.py
tests/integration/targets/firewall/tasks/prepare.yml
tests/integration/targets/firewall_info/tasks/prepare.yml
tests/integration/targets/firewall_resource/tasks/prepare.yml
tests/integration/targets/floating_ip/tasks/test.yml
tests/integration/targets/image_info/tasks/prepare.yml
tests/integration/targets/load_balancer_info/tasks/prepare.yml
tests/integration/targets/load_balancer_target/tasks/prepare.yml
tests/integration/targets/primary_ip/tasks/prepare.yml
tests/integration/targets/server/tasks/test_primary_ips.yml
tests/integration/targets/server/tasks/test_private_network_only.yml
tests/integration/targets/server_info/tasks/prepare.yml
tests/integration/targets/server_network/tasks/prepare.yml
tests/integration/targets/volume/tasks/test.yml

Add a new state for server creation without immediate start, to allow idempotent network customization before starting
server

feat: add new `created` state for idempotent server creation

---

.azure-pipelines/azure-pipelines.yml
.pre-commit-config.yaml
changelogs/fragments/drop-support-for-ansible-2.15.yml
meta/runtime.yml
requirements.txt
tests/sanity/ignore-2.15.txt

ansible-core 2.15 is EOL since Nov 2024.
https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix

feat!: drop support for ansible-core 2.15

---

.azure-pipelines/azure-pipelines.yml
.pre-commit-config.yaml
changelogs/fragments/drop-support-for-ansible-2.16.yml
meta/runtime.yml
requirements.txt
tests/sanity/ignore-2.16.txt

ansible-core 2.16 will be EOL in May 2025.
https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
We are dropping support for ansible-core 2.16 alongside ansible-core 2.15 to prevent cutting another major release in the next month.

feat!: drop support for ansible-core 2.16

---

.azure-pipelines/azure-pipelines.yml

The test jobs for ansible-core 2.18 were missing from the summary.

ci: fix missing jobs in summary

---

.pre-commit-config.yaml
README.md
changelogs/fragments/drop-support-for-python-3.8.yml
pyproject.toml
tests/config.yml

Drop support for python 3.8 which is EOL since Oct 2024.
https://endoflife.date/python
Allow us to upgrade the hcloud-python library.

feat: drop support for python 3.8

---

changelogs/fragments/change-default-inventory-hostvars-prefix.yml
plugins/inventory/hcloud.py

Fixes #616 
The default value for the `hostvars_prefix` option is now set to `hcloud_` to prevent name collision with ansible reserved names when setting the host vars.
inventory

fix!: prevent host variable name collision with ansible reserved names

---

.pre-commit-config.yaml

Enable strict mode when linting the changelog yaml.

test: enable --strict on changelog yaml lint
